version: '3'

services:

  db:
    container_name: $V_DB_CONTAINER
    image: mariadb:latest
    restart: always
    volumes:
      - ${V_AB_PATH}${V_VIRTUAL_HOST}/db_data:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: $V_DB_NAME
      MYSQL_USER: $V_DB_USER
      MYSQL_PASSWORD: $V_DB_PASSWORD

  wp:
    container_name: $V_WP_CONTAINER
    build: .
    depends_on:
      - db
    restart: always
    volumes:
      - ${V_AB_PATH}${V_VIRTUAL_HOST}/html:/var/www/html:rw
    environment:
      WORDPRESS_DB_HOST: $V_DB_CONTAINER
      WORDPRESS_DB_NAME: $V_DB_NAME
      WORDPRESS_DB_USER: $V_DB_USER
      WORDPRESS_DB_PASSWORD: $V_DB_PASSWORD
      WORDPRESS_TABLE_PREFIX: $V_WP_TABLE_PREFIX
      VIRTUAL_HOST: $V_VIRTUAL_HOST
      VIRTUAL_PORT: $V_VIRTUAL_PORT
      LETSENCRYPT_HOST: $V_VIRTUAL_HOST
      LETSENCRYPT_EMAIL: $V_LETSENCRYPT_EMAIL

networks:
  default:
    external:
      name: wordpress-ondemand-api_proxy
